# Generated by Django 2.1.7 on 2019-05-19 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=250)),
                ('ph_no1', models.CharField(max_length=13)),
                ('ph_no2', models.CharField(max_length=13)),
                ('ph_no3', models.CharField(max_length=13)),
                ('ph_no4', models.CharField(max_length=13)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('email3', models.EmailField(max_length=254)),
                ('email4', models.EmailField(max_length=254)),
                ('corp_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiveProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('erd', models.FileField(upload_to='')),
                ('dfd', models.FileField(upload_to='')),
                ('srs', models.FileField(upload_to='')),
                ('Other_Diagram', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('subDate', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('duration', models.IntegerField()),
                ('erd', models.FileField(upload_to='')),
                ('dfd', models.FileField(upload_to='')),
                ('srs', models.FileField(upload_to='')),
                ('Other_Diagram', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectsOnHold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('start_Date', models.DateField()),
                ('form', models.DateField()),
                ('hold_duration', models.IntegerField()),
                ('cause', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('erd', models.FileField(upload_to='')),
                ('dfd', models.FileField(upload_to='')),
                ('srs', models.FileField(upload_to='')),
                ('Other_Diagram', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_Name', models.CharField(max_length=100)),
                ('manager_id', models.IntegerField()),
                ('member_one_Name', models.CharField(max_length=100)),
                ('member_one_id', models.IntegerField()),
                ('member_two_Name', models.CharField(max_length=100)),
                ('member_two_id', models.IntegerField()),
                ('member_three_Name', models.CharField(max_length=100)),
                ('member_three_id', models.IntegerField()),
                ('member_four_Name', models.CharField(max_length=100)),
                ('member_four_id', models.IntegerField()),
                ('member_five_Name', models.CharField(max_length=100)),
                ('members_five_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completed', models.IntegerField()),
                ('client_feedback', models.IntegerField()),
                ('company_feedback', models.IntegerField()),
                ('colleague_feedback', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VpmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('is_availability', models.BooleanField(default=False, max_length=100)),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.VpmUser'),
        ),
        migrations.AddField(
            model_name='projectsonhold',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProjectTeam'),
        ),
        migrations.AddField(
            model_name='projectarchive',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProjectTeam'),
        ),
        migrations.AddField(
            model_name='liveproject',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProjectTeam'),
        ),
    ]
